### ISSUE TITLE
Updates to CORPSE fW calculation

### ISSUE THREAD

**Issue by melanniehartman** [wwieder/biogeochem_testbed_1.1#14]
Add parameter fWmin, the minimum soil moisture effect on decomposition, to the CORPSE parameter file. Save CORPSE fW function (soil moisture effect on soil decomposition) to the output file.

**Comment by wwieder** [comment]
This largely duplicates issue #7, and was addressed with 8714bfc & 8714bfc (adding features to source code) as well as 504fe49 (parameter file)
