### ISSUE TITLE
NPPan

### ISSUE THREAD

**Issue by erbrzostek** [wwieder/biogeochem_testbed_1.1#25]
NPPan is calculated as GPP/2, and used to modify tau in MIMICS.

Should this be updated with the CASAflux%Cnpp that is being calculated?

**Comment by wwieder** [comment]
seems likes this is being done correctly
https://github.com/wwieder/biogeochem_testbed_1.1/blob/e0fbfb92607f12d854ec7f119792b5660eeb04a2/SOURCE_CODE/mimics_cycle_CN.f90#L752

**Comment by melanniehartman** [comment]
This does seem to be a bug. This line is executed every time casacnpdriver is called and a new met.nc file is read in, which is every year during a transient run.  

https://github.com/wwieder/biogeochem_testbed_1.1/blob/e0fbfb92607f12d854ec7f119792b5660eeb04a2/SOURCE_CODE/casa_inout.f90#L4707
