### ISSUE TITLE
code won't compile

### ISSUE THREAD

**Issue by wwieder** [wwieder/biogeochem_testbed_1.1#35]
Hi @melanniehartman I was hoping to try spinning up MIMICS-CN with new parameters, but couldn't get the source code to compile. Not sure if it's because of the compilers now available on CGD machines or something else? 
 https://github.com/wwieder/biogeochem_testbed_1.1/blob/1e3e2d581ab8ccb97ffa19e87b0e286888933057/SOURCE_CODE/README.txt#L1

The error I'm getting is below:

corpse_variable.o corpse_soil_carbon.o corpse_inout.o corpse_cycle.o -L/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib	 -lnetcdff -lm
/usr/bin/ld: warning: libgfortran.so.5, needed by /usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib/libnetcdff.so, not found (try using -rpath or -rpath-link)
/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib/libnetcdff.so: undefined reference to `_gfortran_reshape_4@GFORTRAN_8'
/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib/libnetcdff.so: undefined reference to `_gfortran_runtime_error_at@GFORTRAN_8'
/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib/libnetcdff.so: undefined reference to `_gfortran_shape_4@GFORTRAN_8'
/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib/libnetcdff.so: undefined reference to `_gfortran_reshape_8@GFORTRAN_8'
/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib/libnetcdff.so: undefined reference to `_gfortran_os_error@GFORTRAN_8'
/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib/libnetcdff.so: undefined reference to `_gfortran_string_scan@GFORTRAN_8'
/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib/libnetcdff.so: undefined reference to `_gfortran_size0@GFORTRAN_8'
/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib/libnetcdff.so: undefined reference to `_gfortran_string_len_trim@GFORTRAN_8'
/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib/libnetcdff.so: undefined reference to `_gfortran_internal_unpack@GFORTRAN_8'
/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib/libnetcdff.so: undefined reference to `_gfortran_internal_pack@GFORTRAN_8'
/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-gfortran-8.1.0/lib/libnetcdff.so: undefined reference to `_gfortran_concat_string@GFORTRAN_8'
collect2: error: ld returned 1 exit status
make: *** [casaclm_mimics-cn_corpse] Error 1

**Comment by wwieder** [comment]
found the right readme to load gnu compiler

**Comment by melanniehartman** [comment]
Yes, looks like something on the system changed.  We might have to load a
different module or use different paths in the Makefile. I'll check into it.

Melannie

**Comment by wwieder** [comment]
Don't worry.  I figured it out

**Comment by melanniehartman** [comment]
Great!  What was the problem?

**Comment by wwieder** [comment]
I just forgot to load the right compiler... rookie move

module load compiler/gnu/8.1.0
